config/routes.rb
Rails.application.routes.draw do
  namespace :accounts do
    resource :email, only: %i[ edit update ]
    resource :password, only: %i[ new create edit update ]
    resource :deactivation, only: [] do
      get :confirm
      delete :destroy
    end
  end
  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: %i[] do
    collection do
      get :followings
      get :load_more_followings
      get :communities
      get :load_more_communities
    end
  end
  resources :follows, only: %i[ create destroy ]
  resources :profiles, only: %i[ show new create edit update ]
  resources :municipalities, only: %i[ index ]
  resources :machi_repos do
    collection do
      get :search
      get :load_more
      get :my_machi_repos
      get :load_more_my_machi_repos
      get :bookmarks
      get :load_more_bookmarks
    end

    resources :chats, only: %i[ index create destroy ], module: :machi_repos do
      collection do
        get :load_more
      end
      member do
        get :render_chat
      end
    end
  end
  resources :bookmarks, only: %i[ create destroy ]
  resources :tutorials, only: %i[ new create ]
  resources :accounts, only: %i[ index destroy ]
  resources :communities do
    collection do
      get :community_search
      get :scout_search
      get :scout
      get :members
    end

    member do
      post :join, to: "community_memberships#join"
      post :invite, to: "community_memberships#invite"
    end

    resources :memberships, controller: "community_memberships", only: [], shallow: true do
      member do
        patch :requested_approve
        patch :invited_accept
        patch :requested_reject
        patch :invited_reject
        delete :join_cancel
        delete :invite_cancel
        delete :withdraw
        patch :kick
        patch :update_role
      end
    end

    resources :chats, only: %i[ index create destroy ], module: :communities do
      collection do
        get :load_more
        patch :mark_as_read
      end
      member do
        get :render_chat
      end
    end
  end
  resources :helps, only: %i[ index ]
  get "/terms", to: "pages#terms", as: :terms
  get "/privacy", to: "pages#privacy", as: :privacy
  root "tops#index"

  mount ActionCable.server => "/cable"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :chatable, polymorphic: true

  mount_uploader :image, ChatImageUploader

  validates :message, length: { maximum: 500 }
end

app/models/machi_repo.rb
class MachiRepo < ApplicationRecord
  after_save :assign_tags
  after_initialize do
    self.tag_names ||= tags.map(&:name).join(",") if persisted?
  end

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  attr_accessor :tag_names

  mount_uploader :image, MachiRepoImageUploader

  belongs_to :user
  has_many :machi_repo_tags, dependent: :destroy
  has_many :tags, through: :machi_repo_tags
  has_many :chats, as: :chatable, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user

  enum :info_level, {
    share: 0,         # 共有
    warn: 1,          # 警告
    emergency: 2      # 緊急
  }
  enum :category, {
    crime: 0,         # 防犯・治安
    disaster: 1,      # 災害・気象
    traffic: 2,       # 交通・道路環境
    children: 3,      # 子どもの安全
    animal: 4,        # ペット・動物
    environment: 5,   # 生活環境
    other: 100        # その他・気になること
  }
  enum :hotspot_settings, {
    area: 0,       # エリア指定
    pinpoint: 1    # ピンポイント指定
  }

  validates :title, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 500 }, allow_blank: true
  validates :latitude, presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
  validates :longitude, presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :hotspot_area_radius, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true
  validate  :tag_names_validation

  private

  def tag_names_validation
    return unless tag_names.present?

    tags_array = tag_names.split(",").map(&:strip).reject(&:empty?)

    # タグ数上限チェック
    if tags_array.size > 3
      errors.add(:tag_names, "は3個まで入力できます")
    end

    # 各タグの文字数制限
    tags_array.each do |tag|
      if tag.length > 15
        errors.add(:tag_names, "の各タグは15文字以内で入力してください")
      end
    end

    # 重複チェック
    if tags_array.uniq.size != tags_array.size
      errors.add(:tag_names, "に重複したタグがあります")
    end
  end

  def assign_tags
    return if tag_names.nil?

    self.tags = tag_names.split(",").map(&:strip).reject(&:empty?).uniq.map do |tag_name|
      Tag.find_or_create_by(name: tag_name)
    end
  end
end

app/controllers/communities/chats_controller.rb
class Communities::ChatsController < ApplicationController
  before_action :set_community_and_membership, only: %i[ index load_more ]
  before_action :authorize_access, only: %i[ index ]

  CHAT_PER_PAGE = 15

  def index
    # 無限スクロール対策のため、UNIXタイムスタンプで保存
    snapshot_time = Time.current
    session[:community_chats_snapshot_time] = snapshot_time.to_i

    # 最終ページ判定のため1件多く取得
    raw_chats = @community.chats.includes(user: [ :profile, :community_memberships ]).where("created_at <= ?", snapshot_time).order(created_at: :desc, id: :desc).limit(CHAT_PER_PAGE + 1)

    # 最終ページ判定
    @is_last_page = raw_chats.size <= CHAT_PER_PAGE

    # 表示分切り出し
    @chats = raw_chats.first(CHAT_PER_PAGE)

    # コミュニティに参加しているユーザーのID取得
    set_approved_user_ids

    # 既読数取得
    set_read_counts_hash
  end

  # 無限スクロール用データ取得
  def load_more
    # チャット初期表示時のスナップショット取得
    snapshot_time = Time.at(session[:community_chats_snapshot_time].to_i)
    cursor_created_at = Time.at(params[:previous_last_created].to_i)
    cursor_id = params[:previous_last_id].to_i

    # 最終ページ判定のため1件多く取得
    raw_chats = @community.chats.includes(user: [ :profile, :community_memberships ]).where("created_at < ? OR (created_at = ? AND id < ?)", cursor_created_at, cursor_created_at, cursor_id).order(created_at: :desc, id: :desc).limit(CHAT_PER_PAGE + 1)

    # 最終ページ判定
    @is_last_page = raw_chats.size <= CHAT_PER_PAGE

    # 表示分切り出し
    @chats = raw_chats.first(CHAT_PER_PAGE)

    # 取得データ中最も古い日付を取得
    @new_prev_date = @chats.last&.created_at&.to_date

    # コミュニティに参加しているユーザーのID取得
    set_approved_user_ids

    # 既読数取得
    set_read_counts_hash

    respond_to do |format|
      format.turbo_stream
    end
  end

  # DB登録とブロードキャスト
  def create
    community = Community.find(params[:community_id])
    chat = community.chats.build(chat_params)

    unless chat.save
      render json: {
        status: "ng", errors: chat.errors.full_messages
      }, status: :unprocessable_entity
      return
    end

    # reloadでCarrierWaveの保存後のimage.urlを正確に取得
    chat.reload

    # Action Cableで他のユーザーにも通知
    ActionCable.server.broadcast "community_chat_#{community.id}", {
      type: "create",
      chat_id: chat.id
    }

    render json: { status: "ok" }
  end

  # チャットパーシャル取得
  def render_chat
    @chat = Chat.find(params[:id])
    @user = @chat.user
    @community = @chat.chatable

    # @chatが本当にcommunity_idのまちレポに属するのか確認
    unless @community.id == params[:community_id].to_i
      head :forbidden and return
    end

    @other_chats_on_same_day_exist = @community.chats.where(created_at: @chat.created_at.to_date.all_day).where.not(id: @chat.id).exists?

    @read_counts_hash = {}

    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @chat = current_user.chats.find(params[:id])
    @community = @chat.chatable

    @chat.destroy!

    @other_chats_on_same_day_exist = @community.chats.where(created_at: @chat.created_at.to_date.all_day).where.not(id: @chat.id).exists?

    # Action Cableで他のユーザーにも通知
    ActionCable.server.broadcast "community_chat_#{@community.id}", {
      type: "destroy",
      chat_id: @chat.id,
      user_id: current_user.id,
      other_chats_on_same_day: @other_chats_on_same_day_exist ? nil : @chat.created_at.to_date
    }

    # 自身のチャットはTurbo Streamで画面から削除
    respond_to do |format|
      format.turbo_stream
    end
  end

  # チャットの既読情報更新
  def mark_as_read
    @community = Community.find(params[:community_id])
    last_read_chat_id = params[:last_read_chat_id].to_i

    read = CommunityChatRead.find_or_initialize_by(user: current_user, community: @community)
    last_read_chat_id_before_update = read&.last_read_chat_id || 0

    # IDが進んでいる場合のみ更新
    if read.last_read_chat_id.nil? || last_read_chat_id > read.last_read_chat_id
      read.last_read_chat_id = last_read_chat_id
      read.save

      # 更新前と更新後のlast_read_chat_id間のチャットの既読数を
      # クライアント側でインクリメントする
      ActionCable.server.broadcast "community_chat_#{@community.id}", {
        type: "read",
        user_id: current_user.id,
        last_read_chat_id_before_update: last_read_chat_id_before_update,
        last_read_chat_id_after_update: read.last_read_chat_id
      }
    end

    head :ok
  end

  private

  # 閲覧権限判定
  def authorize_access
    unless current_user.approved_in?(@community)
      redirect_to community_path(@community), alert: "この操作を行う権限がありません"
    end
  end

  def set_community_and_membership
    @community = Community.find(params[:community_id])
    @membership = CommunityMembership.find_by(community_id: @community.id, user_id: current_user.id)
  end

  # 既読数取得
  def set_read_counts_hash
    # 自分のチャットIDだけを抽出
    # 自分以外の既読情報を取得
    my_chat_ids = @chats.select { |chat| chat.user_id == current_user.id }.map(&:id)

    # コミュニティに参加中のユーザーID取得
    approved_users = CommunityMembership.where(community_id: @community.id, status: "approved").select(:user_id)

    # 自分のチャットに対して、既読したユーザ－のIDを配列として保持
    # 自分のチャットIDをキー、既読ユーザーIDの配列をバリューとしてハッシュを作成
    @read_counts_hash = CommunityChatRead
      .where(community_id: @community.id)
      .where.not(user_id: current_user.id)
      .where(user_id: approved_users)
      .pluck(:user_id, :last_read_chat_id)
      .each_with_object(Hash.new { |h, k| h[k] = [] }) do |(user_id, last_read_chat_id), hash|
        my_chat_ids.each do |chat_id|
          hash[chat_id] << user_id if last_read_chat_id >= chat_id
        end
      end
  end

  # コミュニティに参加しているユーザーのIDを取得する
  def set_approved_user_ids
    @approved_user_ids = @community.community_memberships
      .where(status: "approved")
      .pluck(:user_id)
  end

  def chat_params
    params.require(:chat).permit(:message, :image).merge(user: current_user)
  end
end

app/controllers/machi_repos/chats_controller.rb
class MachiRepos::ChatsController < ApplicationController
  before_action :set_machi_repo, only: %i[ index load_more ]

  CHAT_PER_PAGE = 15

  def index
    # 無限スクロール対策のため、UNIXタイムスタンプで保存
    snapshot_time = Time.current
    session[:machi_repo_chats_snapshot_time] = snapshot_time.to_i

    # 最終ページ判定のため1件多く取得
    raw_chats = @machi_repo.chats.includes(:user).where("created_at <= ?", snapshot_time).order(created_at: :desc, id: :desc).limit(CHAT_PER_PAGE + 1)

    # 最終ページ判定
    @is_last_page = raw_chats.size <= CHAT_PER_PAGE

    # 表示分切り出し
    @chats = raw_chats.first(CHAT_PER_PAGE)
  end

  # 無限スクロール用データ取得
  def load_more
    # チャット初期表示時のスナップショット取得
    snapshot_time = Time.at(session[:machi_repo_chats_snapshot_time].to_i)
    cursor_created_at = Time.at(params[:previous_last_created].to_i)
    cursor_id = params[:previous_last_id].to_i

    # 最終ページ判定のため1件多く取得
    raw_chats = @machi_repo.chats.includes(:user).where("created_at < ? OR (created_at = ? AND id < ?)", cursor_created_at, cursor_created_at, cursor_id).order(created_at: :desc, id: :desc).limit(CHAT_PER_PAGE + 1)

    # 最終ページ判定
    @is_last_page = raw_chats.size <= CHAT_PER_PAGE

    # 表示分切り出し
    @chats = raw_chats.first(CHAT_PER_PAGE)

    # 取得データ中最も古い日付を取得
    @new_prev_date = @chats.last&.created_at&.to_date

    respond_to do |format|
      format.turbo_stream
    end
  end

  # DB登録とブロードキャスト
  def create
    machi_repo = MachiRepo.find(params[:machi_repo_id])
    chat = machi_repo.chats.build(chat_params)

    unless chat.save
      render json: {
        status: "ng", errors: chat.errors.full_messages
      }, status: :unprocessable_entity
      return
    end

    # reloadでCarrierWaveの保存後のimage.urlを正確に取得
    chat.reload

    # Action Cableで他のユーザーにも通知
    ActionCable.server.broadcast "machi_repo_chat_#{machi_repo.id}", {
      type: "create",
      chat_id: chat.id
    }

    render json: { status: "ok" }
  end

  # チャットパーシャル取得
  def render_chat
    @chat = Chat.find(params[:id])
    @user = @chat.user
    @machi_repo = @chat.chatable

    # @chatが本当にmachi_repo_idのまちレポに属するのか確認
    unless @machi_repo.id == params[:machi_repo_id].to_i
      head :forbidden and return
    end

    @other_chats_on_same_day_exist = @machi_repo.chats.where(created_at: @chat.created_at.to_date.all_day).where.not(id: @chat.id).exists?

    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @chat = current_user.chats.find(params[:id])
    @machi_repo = @chat.chatable

    @chat.destroy!

    @other_chats_on_same_day_exist = @machi_repo.chats.where(created_at: @chat.created_at.to_date.all_day).where.not(id: @chat.id).exists?

    # Action Cableで他のユーザーにも通知
    ActionCable.server.broadcast "machi_repo_chat_#{@machi_repo.id}", {
      type: "destroy",
      chat_id: @chat.id,
      user_id: current_user.id,
      other_chats_on_same_day: @other_chats_on_same_day_exist ? nil : @chat.created_at.to_date
    }

    # 自身のチャットはTurbo Streamで画面から削除
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_machi_repo
    @machi_repo = MachiRepo.includes(user: :profile).find(params[:machi_repo_id])
  end

  def chat_params
    params.require(:chat).permit(:message, :image).merge(user: current_user)
  end
end

app/views/machi_repos/chats/_chat_remove_button.html.erb
<%= button_to machi_repo_chat_path(machi_repo, chat), method: :delete, data: { controller: "modal", action: "click->modal#confirm", modal_text_value: "削除しますか？" }, class: "hidden absolute top-1/2 -translate-y-1/2 left-0 -translate-x-[calc(100%+8px)] border-2 border-red-700 rounded-xl p-1 shadow-lg bg-red-100" do %>
  <span class="block w-8 aspect-square text-red-700">
    <%= render "shared/icons/delete_icon" %>
  </span>
<% end %>

app/views/machi_repos/chats/destroy.turbo_stream.erb
<%= turbo_stream.remove @chat %>

<% unless @other_chats_on_same_day_exist %>
  <%= turbo_stream.remove "chat-date-#{@chat.created_at&.to_date}" %>
<% end %>

app/views/machi_repos/chats/index.html.erb
<% content_for :head do %>
  <meta name="turbo-cache-control" content="no-cache">
<% end %>

<div data-controller="disable-scroll"></div>

<div class="flex flex-col"
  data-controller="chat"
  data-chat-name-space-value="machi_repos"
  data-chat-channel-name-value="MachiRepoChatChannel"
  data-chat-user-id-value="<%= current_user.id %>"
  data-chat-object-id-value="<%= @machi_repo.id %>"
  data-chat-show-read-receipts-value="false"
  data-chat-textarea-resize-outlet=".textarea-resize"
>
  <div class="transition-all duration-300 ease-in-out"
    data-chat-target="nonChatArea"
  >
    <%= render "machi_repos/machi_repo_info", machi_repo: @machi_repo %>
  </div>
  <div class="border-b-2 border-gray-400 bg-white md:hidden"
    data-chat-target="toggleBarArea"
    data-action="click->chat#toggleNonChatArea"
  >
    <div class="mx-auto w-8 aspect-square"
      data-chat-target="toggleIcon"
    >
      <%= render "shared/icons/eject_icon" %>
    </div>
  </div>

  <section class="relative flex-1 mx-auto w-full max-w-120 shadow-lg">
    <%# スクロール可能表示 %>
    <div class="hidden absolute top-4 left-1/2 -translate-x-1/2 z-1"
      data-chat-target="scrollableIcon"
    >
      <div class="bounce w-8 aspect-square border rounded-full bg-white">
        <%= render "shared/icons/arrow_upward_icon" %>
      </div>
    </div>
    <%# チャットエリア %>
    <div
      id="chat-section"
      class="opacity-0 px-2 overflow-y-auto transition-all duration-300 ease-in-out"
      data-chat-target="container"
    >
      <%# チャットエリア(チャット表示) %>
      <div
        id="chat-area"
        data-chat-target="chatArea"
      >
        <%# 既読数管理用ID %>
        <input type="hidden"
          id="last-read-chat-id"
          value="<%= @chats.first&.id || 0 %>"
          data-chat-target="lastReadChatId"
        >
        <%# 最終ページ判定 %>
        <input type="hidden"
          id="last-page-marker"
          value="<%= @is_last_page %>"
          data-chat-target="lastPageMarker"
        >
        <%# 取得データの最後の更新日時を保持 %>
        <input type="hidden"
          id="previous-last-created"
          value="<%= @chats.last&.created_at&.to_i %>"
          data-chat-target="previousLastCreated"
        >
        <%# 取得データの最後のIDを保持 %>
        <input type="hidden"
          id="previous-last-id"
          value="<%= @chats.last&.id %>"
          data-chat-target="previousLastId"
        >
        <%# chatの初期表示 %>
        <div id="chats">
          <%# 日付表示 %>
          <% top_chat_date = @chats.last&.created_at&.to_date %>
          <% if top_chat_date %>
            <%= render "shared/chat_date_block", date: top_chat_date %>
          <% end %>

          <% previous_date = top_chat_date %>
          <% @chats.reverse_each do |chat| %>
            <% chat_date = chat.created_at.to_date %>
            <% if previous_date != chat_date %>
              <%= render "shared/chat_date_block", date: chat_date %>
            <% end %>
            <% previous_date = chat_date %>

            <% if current_user == chat.user %>
              <%= render "shared/chat_mine", chat: chat, chat_color_class_name: "#{@machi_repo.info_level}", read_counts_hash: nil, remove_button: render("machi_repos/chats/chat_remove_button", machi_repo: @machi_repo, chat: chat) %>
            <% else %>
              <%= render "shared/chat_others", nickname: chat.user.profile.nickname, chat: chat %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <%= form_with url: "#", method: :post, local: true, class:"absolute bottom-[-40px] shadow-lg w-full max-w-[480px]" do |form| %>
      <div data-chat-target="textareaForm">
        <div class="flex items-end p-1 bg-white">
          <div data-action="click->chat#toggleChatForm" class="flex-shrink-0 w-8 aspect-square text-green-600">
            <%= render "shared/icons/image_icon" %>
          </div>

          <%= form.text_area :message,
            maxlength: 500,
            rows: 1,
            placeholder: "メッセージを入力してください",
            class: "textarea-resize rounded-xl px-2 py-1 w-full resize-none overflow-hidden bg-gray-100",
            data: {
              controller: "textarea-resize",
              textarea_resize_target: "textarea",
              action: "input->textarea-resize#resize",
              chat_target: "textarea",
            }
          %>

          <%= form.button id: "message-btn", type: "button", data: { action: "click->chat#postMessage"} do %>
            <div class="flex-shrink-0 w-8 aspect-square text-blue-500">
              <%= render "shared/icons/send_full_icon" %>
            </div>
          <% end %>
        </div>
      </div>

      <div data-chat-target="fileFieldForm" class="hidden">
        <div class="flex items-end p-1 bg-white">
          <div data-action="click->chat#toggleChatForm" class="flex-shrink-0 w-8 aspect-square text-rose-600">
            <%= render "shared/icons/chat_add_on_icon" %>
          </div>

          <%= form.file_field :image,
            class: "rounded-xl px-2 py-1 w-full bg-gray-100",
            data: { chat_target: "fileField" }
          %>

          <%= form.button id: "image-btn", type: "button", data: { action: "click->chat#uploadImage"} do %>
            <div class="flex-shrink-0 w-8 aspect-square text-blue-500">
              <%= render "shared/icons/upload_icon" %>
            </div>
          <% end %>
        </div>
      </div>
      <div
        data-chat-target="spinner"
        class="hidden absolute top-[0px] right-[0px] bottom-[0px] w-10 aspect-square bg-white z-1">
        <div class="flex justify-center items-center w-full h-full">
          <div class="w-6 aspect-square border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
        </div>
      </div>
    <% end %>

    <%# 新着チャット表示 %>
    <div
      data-action="click->chat#scrollNewChat"
      data-chat-target="newIcon"
      class="hidden absolute bottom-2 right-2 shadow-lg border-2 border-orange-400 rounded-full w-[60px] aspect-square text-center leading-[60px] bg-white text-orange-500 font-semibold z-1 md:right-4">
      New!!
    </div>
  </section>
</div>

app/views/machi_repos/chats/load_more.turbo_stream.erb
<%= turbo_stream.prepend "chats" do %>
  <%# 日付表示 %>
  <% previous_date = @new_prev_date %>
  <%= render "shared/chat_date_block", date: previous_date %>
  <% @chats.reverse_each do |chat| %>
    <% chat_date = chat.created_at.to_date %>
    <% if previous_date != chat_date %>
      <%= render "shared/chat_date_block", date: chat_date %>
    <% end %>
    <% previous_date = chat_date %>

    <%# レコード表示 %>
    <% if current_user == chat.user %>
      <%= render "shared/chat_mine", chat: chat, chat_color_class_name: "#{@machi_repo.info_level}", read_counts_hash: nil, remove_button: render("machi_repos/chats/chat_remove_button", machi_repo: @machi_repo, chat: chat) %>
    <% else %>
      <%= render "shared/chat_others", nickname: chat.user.profile.nickname, chat: chat %>
    <% end %>
  <% end %>
<% end %>

<%# 最終ページ判定 %>
<%= turbo_stream.replace "last-page-marker" do %>
  <input type="hidden"
    id="last-page-marker"
    value="<%= @is_last_page %>"
    data-chat-target="lastPageMarker"
  >
<% end %>

<%# 取得データの最後の更新日時を保持 %>
<%= turbo_stream.replace "previous-last-created" do %>
  <input type="hidden"
    id="previous-last-created"
    value="<%= @chats.last&.created_at&.to_i %>"
    data-chat-target="previousLastCreated"
  >
<% end %>

<%# 取得データの最後のIDを保持 %>
<%= turbo_stream.replace "previous-last-id" do %>
  <input type="hidden"
    id="previous-last-id"
    value="<%= @chats.last&.id %>"
    data-chat-target="previousLastId"
  >
<% end %>

app/views/machi_repos/chats/render_chat.turbo_stream.erb
<%= turbo_stream.append "chat-area" do %>
  <% unless @other_chats_on_same_day_exist %>
    <%= render "shared/chat_date_block", date: @chat.created_at.to_date %>
  <% end %>
  <% if current_user == @user %>
    <%= render "shared/chat_mine", chat: @chat, chat_color_class_name: "#{@machi_repo.info_level}", read_counts_hash: nil, remove_button: render("machi_repos/chats/chat_remove_button", machi_repo: @machi_repo, chat: @chat) %>
  <% else %>
    <%= render "shared/chat_others", nickname: @user.profile.nickname, chat: @chat %>
  <% end %>
<% end %>