config/routes.rb
Rails.application.routes.draw do
  namespace :accounts do
    resource :email, only: %i[ edit update ]
    resource :password, only: %i[ new create edit update ]
    resource :deactivation, only: [] do
      get :confirm
      delete :destroy
    end
  end
  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: %i[] do
    collection do
      get :followings
      get :load_more_followings
      get :communities
      get :load_more_communities
    end
  end
  resources :follows, only: %i[ create destroy ]
  resources :profiles, only: %i[ show new create edit update ]
  resources :municipalities, only: %i[ index ]
  resources :machi_repos do
    collection do
      get :search
      get :load_more
      get :my_machi_repos
      get :load_more_my_machi_repos
      get :bookmarks
      get :load_more_bookmarks
    end

    resources :chats, only: %i[ index create destroy ], module: :machi_repos do
      collection do
        get :load_more
      end
      member do
        get :render_chat
      end
    end
  end
  resources :bookmarks, only: %i[ create destroy ]
  resources :tutorials, only: %i[ new create ]
  resources :accounts, only: %i[ index destroy ]
  resources :communities do
    collection do
      get :community_search
      get :scout_search
      get :scout
      get :members
    end

    member do
      post :join, to: "community_memberships#join"
      post :invite, to: "community_memberships#invite"
    end

    resources :memberships, controller: "community_memberships", only: [], shallow: true do
      member do
        patch :requested_approve
        patch :invited_accept
        patch :requested_reject
        patch :invited_reject
        delete :join_cancel
        delete :invite_cancel
        delete :withdraw
        patch :kick
        patch :update_role
      end
    end

    resources :chats, only: %i[ index create destroy ], module: :communities do
      collection do
        get :load_more
        patch :mark_as_read
      end
      member do
        get :render_chat
      end
    end
  end
  resources :helps, only: %i[ index ]
  get "/terms", to: "pages#terms", as: :terms
  get "/privacy", to: "pages#privacy", as: :privacy
  root "tops#index"

  mount ActionCable.server => "/cable"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/machi_repo.rb
class MachiRepo < ApplicationRecord
  after_save :assign_tags
  after_initialize do
    self.tag_names ||= tags.map(&:name).join(",") if persisted?
  end

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  attr_accessor :tag_names

  mount_uploader :image, MachiRepoImageUploader

  belongs_to :user
  has_many :machi_repo_tags, dependent: :destroy
  has_many :tags, through: :machi_repo_tags
  has_many :chats, as: :chatable, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user

  enum :info_level, {
    share: 0,         # 共有
    warn: 1,          # 警告
    emergency: 2      # 緊急
  }
  enum :category, {
    crime: 0,         # 防犯・治安
    disaster: 1,      # 災害・気象
    traffic: 2,       # 交通・道路環境
    children: 3,      # 子どもの安全
    animal: 4,        # ペット・動物
    environment: 5,   # 生活環境
    other: 100        # その他・気になること
  }
  enum :hotspot_settings, {
    area: 0,       # エリア指定
    pinpoint: 1    # ピンポイント指定
  }

  validates :title, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 500 }, allow_blank: true
  validates :latitude, presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
  validates :longitude, presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :hotspot_area_radius, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true
  validate  :tag_names_validation

  private

  def tag_names_validation
    return unless tag_names.present?

    tags_array = tag_names.split(",").map(&:strip).reject(&:empty?)

    # タグ数上限チェック
    if tags_array.size > 3
      errors.add(:tag_names, "は3個まで入力できます")
    end

    # 各タグの文字数制限
    tags_array.each do |tag|
      if tag.length > 15
        errors.add(:tag_names, "の各タグは15文字以内で入力してください")
      end
    end

    # 重複チェック
    if tags_array.uniq.size != tags_array.size
      errors.add(:tag_names, "に重複したタグがあります")
    end
  end

  def assign_tags
    return if tag_names.nil?

    self.tags = tag_names.split(",").map(&:strip).reject(&:empty?).uniq.map do |tag_name|
      Tag.find_or_create_by(name: tag_name)
    end
  end
end

app/controllers/machi_repos/chats_controller.rb
class MachiRepos::ChatsController < ApplicationController
  before_action :set_machi_repo, only: %i[ index load_more ]

  CHAT_PER_PAGE = 15

  def index
    # 無限スクロール対策のため、UNIXタイムスタンプで保存
    snapshot_time = Time.current
    session[:machi_repo_chats_snapshot_time] = snapshot_time.to_i

    # 最終ページ判定のため1件多く取得
    raw_chats = @machi_repo.chats.includes(:user).where("created_at <= ?", snapshot_time).order(created_at: :desc, id: :desc).limit(CHAT_PER_PAGE + 1)

    # 最終ページ判定
    @is_last_page = raw_chats.size <= CHAT_PER_PAGE

    # 表示分切り出し
    @chats = raw_chats.first(CHAT_PER_PAGE)
  end

  # 無限スクロール用データ取得
  def load_more
    # チャット初期表示時のスナップショット取得
    snapshot_time = Time.at(session[:machi_repo_chats_snapshot_time].to_i)
    cursor_created_at = Time.at(params[:previous_last_created].to_i)
    cursor_id = params[:previous_last_id].to_i

    # 最終ページ判定のため1件多く取得
    raw_chats = @machi_repo.chats.includes(:user).where("created_at < ? OR (created_at = ? AND id < ?)", cursor_created_at, cursor_created_at, cursor_id).order(created_at: :desc, id: :desc).limit(CHAT_PER_PAGE + 1)

    # 最終ページ判定
    @is_last_page = raw_chats.size <= CHAT_PER_PAGE

    # 表示分切り出し
    @chats = raw_chats.first(CHAT_PER_PAGE)

    # 取得データ中最も古い日付を取得
    @new_prev_date = @chats.last&.created_at&.to_date

    respond_to do |format|
      format.turbo_stream
    end
  end

  # DB登録とブロードキャスト
  def create
    machi_repo = MachiRepo.find(params[:machi_repo_id])
    chat = machi_repo.chats.build(chat_params)

    unless chat.save
      render json: {
        status: "ng", errors: chat.errors.full_messages
      }, status: :unprocessable_entity
      return
    end

    # reloadでCarrierWaveの保存後のimage.urlを正確に取得
    chat.reload

    # Action Cableで他のユーザーにも通知
    ActionCable.server.broadcast "machi_repo_chat_#{machi_repo.id}", {
      type: "create",
      chat_id: chat.id
    }

    render json: { status: "ok" }
  end

  # チャットパーシャル取得
  def render_chat
    @chat = Chat.find(params[:id])
    @user = @chat.user
    @machi_repo = @chat.chatable

    # @chatが本当にmachi_repo_idのまちレポに属するのか確認
    unless @machi_repo.id == params[:machi_repo_id].to_i
      head :forbidden and return
    end

    @other_chats_on_same_day_exist = @machi_repo.chats.where(created_at: @chat.created_at.to_date.all_day).where.not(id: @chat.id).exists?

    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @chat = current_user.chats.find(params[:id])
    @machi_repo = @chat.chatable

    @chat.destroy!

    @other_chats_on_same_day_exist = @machi_repo.chats.where(created_at: @chat.created_at.to_date.all_day).where.not(id: @chat.id).exists?

    # Action Cableで他のユーザーにも通知
    ActionCable.server.broadcast "machi_repo_chat_#{@machi_repo.id}", {
      type: "destroy",
      chat_id: @chat.id,
      user_id: current_user.id,
      other_chats_on_same_day: @other_chats_on_same_day_exist ? nil : @chat.created_at.to_date
    }

    # 自身のチャットはTurbo Streamで画面から削除
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_machi_repo
    @machi_repo = MachiRepo.includes(user: :profile).find(params[:machi_repo_id])
  end

  def chat_params
    params.require(:chat).permit(:message, :image).merge(user: current_user)
  end
end

app/controllers/machi_repos_controller.rb
class MachiReposController < ApplicationController
  include InfiniteScroll

  before_action :set_mytown_location, only: %i[ new edit ]

  MACHI_REPO_PER_PAGE = 12

  def index
    raw_search_params = {}
    # 前回の表示結果があれば取得する
    if session[:machi_repos_home_display_status].present?
      raw_search_params = session[:machi_repos_home_display_status]
      raw_search_params["address"] = nil
    end

    # 表示用データを取得する
    prepare_search_data(raw_search_params)
    respond_to do |format|
      format.html
    end
  end

  def search
    # 表示用データを取得する
    prepare_search_data(search_params)
    respond_to do |format|
      format.turbo_stream
    end
  end

  # "まち"のまちレポ無限スクロールデータ取得
  def load_more
    # まちレポ全体表示時のスナップショット取得
    snapshot_time = Time.at(session[:machi_repos_snapshot_time].to_i)
    cursor_updated_at = Time.at(params[:previous_last_updated].to_i)
    cursor_id = params[:previous_last_id].to_i

    form_params = enrich_search_params_with_coordinates(search_params)

    @search_form = MachiRepoSearchForm.new(form_params)
    search_result = @search_form.search_machi_repos.where("machi_repos.updated_at <= ?", snapshot_time)

    # データの総数を取得する
    @machi_repos_count = search_result.size

    # 最終ページ判定のため1件多く取得
    raw_machi_repos = search_result
                      .where("machi_repos.updated_at < ? OR (machi_repos.updated_at = ? AND id < ?)", cursor_updated_at, cursor_updated_at, cursor_id)
                      .order("machi_repos.updated_at DESC, machi_repos.id DESC")
                      .limit(MACHI_REPO_PER_PAGE + 1)
    # 最終ページ判定
    @is_last_page = raw_machi_repos.size <= MACHI_REPO_PER_PAGE

    # 表示分切り出し
    @machi_repos = raw_machi_repos.first(MACHI_REPO_PER_PAGE)

    respond_to do |format|
      format.turbo_stream
    end
  end

  def show
    @machi_repo = MachiRepo.includes(user: :profile).find_by(id: params[:id])

    unless @machi_repo
      redirect_back fallback_location: machi_repos_path, alert: "指定されたまちレポが見つかりませんでした。"
      return
    end

    # ログイン済み & 投稿者本人でなければ、views_countをインクリメント
    if user_signed_in? && current_user.id != @machi_repo.user_id
      track_view_count(@machi_repo.id)
      # インクリメントされたviews_countを取得
      @machi_repo.reload
    end
  end

  def new
    @machi_repo = MachiRepo.new(
      address: @mytown_address,
      latitude: @mytown_latitude,
      longitude: @mytown_longitude
    )
  end

  def create
    @machi_repo = current_user.machi_repos.build(machi_repo_params)
    if @machi_repo.save
      redirect_to @machi_repo, notice: "まちレポを作成しました"
    else
      append_errors_to_flash(@machi_repo, "作成")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @machi_repo = current_user.machi_repos.includes(user: :profile).find(params[:id])
  end

  def update
    @machi_repo = current_user.machi_repos.find(params[:id])
    if @machi_repo.update(machi_repo_params)
      redirect_to machi_repo_path(@machi_repo), notice: "まちレポを更新しました"
    else
      append_errors_to_flash(@machi_repo, "更新")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    machi_repo = current_user.machi_repos.find(params[:id])
    machi_repo.destroy!
    redirect_to machi_repos_path, notice: "まちレポを削除しました", status: :see_other
  end

  # マイまちレポ
  def my_machi_repos
    @user = User.find(params[:user_id])
    total_records = @user.machi_repos.order(updated_at: :desc)
    load_init_data("machi_repos", total_records, MACHI_REPO_PER_PAGE)
    @machi_repos = @records
    @machi_repos_count = @total_records_count
  end

  # マイまちレポの無限スクロール
  def load_more_my_machi_repos
    user = User.find(params[:user_id])
    total_records = user.machi_repos.order(updated_at: :desc)
    load_more_data("machi_repos", total_records, MACHI_REPO_PER_PAGE)
    respond_to do |format|
      format.turbo_stream
    end
  end

  # マイページのブックマーク
  def bookmarks
    total_records = current_user.bookmark_machi_repos.order(updated_at: :desc)
    load_init_data("machi_repos", total_records, MACHI_REPO_PER_PAGE)
    @machi_repos = @records
    @machi_repos_count = @total_records_count
  end

  # マイページのブックマークの無限スクロール
  def load_more_bookmarks
    total_records = current_user.bookmark_machi_repos.order(updated_at: :desc)
    load_more_data("machi_repos", total_records, MACHI_REPO_PER_PAGE)
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def prepare_search_data(raw_search_params)
    # インスタンス変数初期化
    @snapshot_time = Time.current
    @search_form = MachiRepoSearchForm.new
    @near_hotspots = []
    @machi_repos = []
    @machi_repos_count = 0
    @is_last_page = true

    # 検索用ストロングパラメータに値を追加
    form_params = enrich_search_params_with_coordinates(raw_search_params)
    if form_params.blank?
      @is_error = true
      return
    end

    # 無限スクロール対策のため、UNIXタイムスタンプで保存
    session[:machi_repos_snapshot_time] = @snapshot_time.to_i

    # sessionに画面表示の条件を保持しておく
    session[:machi_repos_home_display_status] = form_params.to_h

    @search_form = MachiRepoSearchForm.new(form_params)

    unless @search_form.valid?
      flash.now[:alert] = [ "検索条件を確認してください" ] + @search_form.errors.full_messages
    end

    # 周辺のホットスポット取得
    @near_hotspots = @search_form.search_near_hotspots.order("machi_repos.updated_at DESC, machi_repos.id DESC")

    # "まち"のまちレポ取得
    search_result = @search_form.search_machi_repos.where("machi_repos.updated_at <= ?", @snapshot_time)
    # データ総数取得
    @machi_repos_count = search_result.size
    # 無限スクロール前のデータ取得
    @machi_repos = search_result.order("machi_repos.updated_at DESC, machi_repos.id DESC").limit(MACHI_REPO_PER_PAGE)
    # 最終ページのデータか判定(初期表示のため下記でOK)
    @is_last_page = @machi_repos_count <= MACHI_REPO_PER_PAGE
  end

  # search_paramsにマップ情報を追加する
  def enrich_search_params_with_coordinates(raw_search_params)
    form_params = raw_search_params

    results =
      if form_params["address"].present?
        Geocoder.search(form_params["address"])
      elsif form_params["latitude"].present? && form_params["longitude"].present?
        Geocoder.search([ form_params["latitude"], form_params["longitude"] ])
      else
        Geocoder.search(current_user.mytown_address)
      end

    # ジオコーディング・リバースジオコーディング失敗
    if results.blank? || results.first.blank?
      flash.now[:alert] = [ "住所が見つかりませんでした" ]
      return nil
    end

    result = results.first
    if result.country_code != "JP"
      flash.now[:alert] = [ "日本国内の住所を入力してください" ]
      return nil
    end

    if result.state.blank? || result.city.blank?
      flash.now[:alert] = [ "都道府県または市区町村が特定できませんでした" ]
      return nil
    end

    @address = result.state + result.city
    @latitude = form_params["latitude"].presence || result.coordinates[0]
    @longitude = form_params["longitude"].presence || result.coordinates[1]

    form_params["address"] = @address
    form_params["latitude"] = @latitude
    form_params["longitude"] = @longitude

    form_params
  end

  # エラーメッセージを追加する
  def append_errors_to_flash(record, action_name)
    flash.now[:alert] = [ "まちレポの#{action_name}に失敗しました" ]
    flash.now[:alert] += record.errors.full_messages if record.errors.any?
  end

  # マイタウン情報を設定する
  def set_mytown_location
    @mytown_address = current_user.mytown_address
    geocoding = Geocoder.search(@mytown_address).first.coordinates
    @mytown_latitude = geocoding[0]
    @mytown_longitude = geocoding[1]
  end

  # まちレポ詳細の閲覧数登録処理
  def track_view_count(machi_repo_id)
    cookie_key = "viewed_machi_repo_#{machi_repo_id}"

    # 短時間に同じユーザーの閲覧で何度もインクリメントされないようにする
    unless cookies[cookie_key]
      MachiRepo.increment_counter(:views_count, machi_repo_id)
      # 有効期限を24時間に設定
      cookies[cookie_key] = { value: true, expires: 24.hours.from_now }
    end
  end

  # DB登録時のストロングパラメータ取得
  def machi_repo_params
    params.require(:machi_repo).permit(
      :title, :info_level, :category, :description,
      :hotspot_settings, :hotspot_area_radius,
      :address, :latitude, :longitude,
      :image, :image_cache, :tag_names
    )
  end

  # 検索時のストロングパラメータ取得
  def search_params
    params.fetch(:search, {}).permit(
      :title, :info_level, :category, :tag_names, :tag_match_type,
      :display_range_radius, :display_hotspot_count,
      :start_date, :end_date, :latitude, :longitude, :address
    )
  end
end

app/views/machi_repos/_bookmark_infinite_scroll.html.erb
<div class="machi-repo-cards relative"
      id="my-machi-repos"
>
  <%# 一覧表示 %>
  <% machi_repos.each do |machi_repo| %>
    <%= render "shared/machi_repo_card", machi_repo: machi_repo %>
  <% end %>
</div>

app/views/machi_repos/_machi_repo_cards_infinite_scroll.html.erb
<div class="machi-repo-cards relative"
      id="my-machi-repos"
>
  <%# 一覧表示 %>
  <% machi_repos.each do |machi_repo| %>
    <%= render "shared/machi_repo_card", machi_repo: machi_repo %>
  <% end %>
</div>

app/views/machi_repos/_machi_repo_info.html.erb
<%# info_levelに応じてbody背景色変更 %>
<% content_for :body_class, "bg-#{machi_repo.info_level}" %>

<section class="border-b-2 border-gray-400">
  <div class="text-center">
    <div class="mb-4 mx-auto pt-4 px-2 max-w-[550px]">
      <div class="flex justify-between items-center mx-auto mb-4">
        <div class="flex items-center <%= "text-#{machi_repo.info_level}" %>">
          <%# info_levelに応じてアイコン変更 %>
          <div class="w-10 aspect-square">
            <% if machi_repo.emergency? %>
              <%= render "shared/icons/emergency_full_icon" %>
              <% info_level_text = "緊急" %>
            <% elsif machi_repo.warn? %>
              <%= render "shared/icons/warn_full_icon" %>
              <% info_level_text = "警告" %>
            <% else %>
              <%= render "shared/icons/share_full_icon" %>
              <% info_level_text = "共有" %>
            <% end %>
          </div>
          <span class="text-xl font-bold"><%= info_level_text %></span>
        </div>
        <%# ブックマーク %>
        <% if current_user != machi_repo.user %>
          <span class="flex-shrink-0 ml-auto w-8 aspect-square">
            <%= render "machi_repos/bookmarks/bookmark_buttons", machi_repo: machi_repo %>
          </span>
        <% end %>
      </div>

      <%# タイトル %>
      <div class="mx-auto w-[90%] md:w-full">
        <h2 class="inline-block px-4 py-2 min-w-[50%] <%= "title-bg-#{machi_repo.info_level}" %> text-white text-xl font-bold rounded shadow">
          <%= machi_repo.title %>
        </h2>
      </div>
    </div>

    <%# ヘルプ %>
    <div class="mb-2 mx-auto w-full max-w-120">
      <%= render "shared/help_carousel",
        items: [
          { title: "チャット方法", content_partial: "shared/helps/how_to_chat/content" }
        ]
      %>
    </div>

    <nav class="md:fixed md:top-[280px] md:left-[50px]">
      <ul class="flex justify-center gap-12 mb-4 md:flex-col">
        <% if controller_name == "machi_repos" && action_name == "show"
          current_page = "detail"
        elsif controller_name == "chats"
          current_page = "chat"
        else
          current_page = ""
        end %>
        <!-- 詳細アイコン -->
        <li>
          <%= link_to machi_repo_path(machi_repo), class: "icon-circle-wrapper #{"icon-circle-wrapper-current" if current_page == "detail"}", id: "detail-link" do %>
            <div class="icon-circle <%= "icon-circle-current" if current_page == "detail" %>">
              <div class="w-8 aspect-square">
                <%= render "shared/icons/description_icon" %>
              </div>
            </div>
            <span class="icon-circle-text">詳細</span>
          <% end %>
        </li>
        <!-- チャットアイコン -->
        <li>
          <%= link_to machi_repo_chats_path(machi_repo), class: "icon-circle-wrapper #{"icon-circle-wrapper-current" if current_page == "chat"}", id: "chat-link" do %>
            <div class="icon-circle <%= "icon-circle-current" if current_page == "chat" %>">
              <div class="w-8 aspect-square">
                <%= render "shared/icons/chat_icon" %>
              </div>
            </div>
            <span class="icon-circle-text">チャット</span>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</section>

app/views/machi_repos/bookmarks.html.erb
<%= render "shared/mypage_info" %>

<section class="mx-auto pt-4 pb-8 max-w-120 lg:max-w-175 xl:max-w-250">
  <%= render "shared/infinite_scroll_item",
    controller: "machi_repos",
    action: "load_more_bookmarks",
    user_id: 0,
    title: "まちレポブックマーク一覧",
    objects_count: @machi_repos_count,
    snapshot_time: @snapshot_time,
    is_last_page: @is_last_page,
    objects: @machi_repos,
    contents: render("machi_repo_cards_infinite_scroll", machi_repos: @machi_repos)
  %>
</section>

app/views/machi_repos/edit.html.erb
<% content_for :title, "まちレポ編集" %>

<div class="text-center">
  <h2 class="mb-6">
    <span class="header1"><%= t('.title') %></span>
    <p>投稿したまちレポを編集できます</p>
  </h2>

  <div class="mx-auto mb-4 w-full max-w-[500px]">
    <%= link_to "< 詳細へ戻る", machi_repo_path(@machi_repo), class: "link underline inline-block mx-auto w-full max-w-[300px] text-left"  %>
  </div>
  <%= render "form", machi_repo: @machi_repo %>
</div>

app/views/machi_repos/index.html.erb
<% content_for :title, "まちレポ" %>

<div class="text-center">
  <div>
    <h2>
      <span class="header1"><%= t('.title') %></span>
    </h2>
    <p>
      "まち"の安心・安全情報を<br>
      表示します
    </p>
  </div>

  <div class="mb-2">
    <%= render "shared/help_carousel",
      items: [
        { title: "まちレポの閲覧方法", content_partial: "shared/helps/how_to_view_machi_repos/content" },
        { title: "周辺のホットスポット", content_partial: "shared/helps/nearby_hotspots/content" },
        { title: "\"まち\"のまちレポ一覧", content_partial: "shared/helps/towns_machi_repos/content" }
      ]
    %>
  </div>

  <% unless @current_user.machi_repos.exists? %>
    <div id="tutorial" class="mx-auto mb-6 border border-orange-400 rounded-full py-2 shadow-lg w-[300px] bg-[#FFC34D]">
      <%= link_to "\"まちレポ\"を作成してみませんか？", new_tutorial_path, class: "link underline" %>
    </div>
  <% end %>

  <%= render "index_map",
    address: @address,
    latitude: @latitude,
    longitude: @longitude,
    near_hotspots: @near_hotspots,
    machi_repos: @machi_repos,
    machi_repos_count: @machi_repos_count,
    is_last_page: @is_last_page
  %>
</div>

app/views/machi_repos/load_more.turbo_stream.erb
<%= turbo_stream.append "machi_repos" do %>
  <% @machi_repos.each do |machi_repo| %>
    <%= render "shared/machi_repo_card", machi_repo: machi_repo %>
  <% end %>
<% end %>

<%= turbo_stream.replace "machi-repos-last-page-marker" do %>
  <div
    id="machi-repos-last-page-marker"
    data-last-page="<%= @is_last_page %>"
    class="hidden"
  ></div>
<% end %>

<%= turbo_stream.replace "machi-repos-previous-last-data" do %>
  <div
    id="machi-repos-previous-last-data"
    data-previous-last-updated="<%= @machi_repos.last&.updated_at&.to_i %>"
    data-previous-last-id="<%= @machi_repos.last&.id %>"
    class="hidden"
  ></div>
<% end %>

<%= turbo_stream.replace "machi-repos-count" do %>
  <span id="machi-repos-count">
    <%= @machi_repos_count %>
  </span>
<% end %>

app/views/machi_repos/load_more_bookmarks.turbo_stream.erb
<%# 一覧に追加 %>
<%= turbo_stream.append "my-machi-repos" do %>
  <% @records.each do |record| %>
    <%= render "shared/machi_repo_card", machi_repo: record %>
  <% end %>
<% end %>

<%# 最終ページ判定更新 %>
<%= turbo_stream.replace "last-page-marker" do %>
  <input type="hidden"
    id="last-page-marker"
    value="<%= @is_last_page %>"
    data-infinite-scroll-target="lastPageMarker"
  >
<% end %>

<%# 最終データの更新日時更新 %>
<%= turbo_stream.replace "previous-last-updated" do %>
  <input type="hidden"
    id="previous-last-updated"
    value="<%= @records.last&.updated_at&.to_i %>"
    data-infinite-scroll-target="previousLastUpdated"
  >
<% end %>

<%# 最終データのID更新 %>
<%= turbo_stream.replace "previous-last-id" do %>
  <input type="hidden"
    id="previous-last-id"
    value="<%= @records.last&.id %>"
    data-infinite-scroll-target="previousLastId"
  >
<% end %>

<%# 総数表示更新 %>
<%= turbo_stream.update "objects-count" do %>
  <%= @total_records_count %>
<% end %>

app/views/machi_repos/load_more_my_machi_repos.turbo_stream.erb
<%# 一覧に追加 %>
<%= turbo_stream.append "my-machi-repos" do %>
  <% @records.each do |record| %>
    <%= render "shared/machi_repo_card", machi_repo: record %>
  <% end %>
<% end %>

<%# 最終ページ判定更新 %>
<%= turbo_stream.replace "last-page-marker" do %>
  <input type="hidden"
    id="last-page-marker"
    value="<%= @is_last_page %>"
    data-infinite-scroll-target="lastPageMarker"
  >
<% end %>

<%# 最終データの更新日時更新 %>
<%= turbo_stream.replace "previous-last-updated" do %>
  <input type="hidden"
    id="previous-last-updated"
    value="<%= @records.last&.updated_at&.to_i %>"
    data-infinite-scroll-target="previousLastUpdated"
  >
<% end %>

<%# 最終データのID更新 %>
<%= turbo_stream.replace "previous-last-id" do %>
  <input type="hidden"
    id="previous-last-id"
    value="<%= @records.last&.id %>"
    data-infinite-scroll-target="previousLastId"
  >
<% end %>

<%# 総数表示更新 %>
<%= turbo_stream.update "objects-count" do %>
  <%= @total_records_count %>
<% end %>

app/views/machi_repos/my_machi_repos.html.erb
<% if current_user == @user %>
  <%= render "shared/mypage_info" %>
<% else %>
  <%= render "shared/userpage_info", user: @user %>
<% end %>

<section class="mx-auto pt-4 pb-8 max-w-120 lg:max-w-175 xl:max-w-250">
  <%= render "shared/infinite_scroll_item",
    controller: "machi_repos",
    action: "load_more_my_machi_repos",
    user_id: @user.id,
    title: "マイまちレポ一覧",
    objects_count: @machi_repos_count,
    snapshot_time: @snapshot_time,
    is_last_page: @is_last_page,
    objects: @machi_repos,
    contents: render("machi_repo_cards_infinite_scroll", machi_repos: @machi_repos)
  %>
</section>